networks:
  localnetwork:
services:
  db:
    image: mysql:8.0.33
    command: --default-authentication-plugin=caching_sha2_password
    restart: always
    env_file: ./db/.env
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql/init:/docker-entrypoint-initdb.d:ro
      - ./db/mysql/data:/var/lib/mysql
    networks:
      - localnetwork
  web:
    image: dsp8ef9/psite_web:latest
    build: ../psite-web/.
    env_file: ./web/.env
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./web/apache/log:/var/log/apache2
      - ./web/php/fpm/log:/var/log/php-fpm
      - ./web/apache/ssl:/etc/apache2/ssl:ro
      - ./web/apache/htpasswd:/var/www/htpasswd:ro
    networks:
      - localnetwork
  job:
    image: dsp8ef9/psite_job:latest
    build: ../psite-job/.
    env_file: ./job/.env
    volumes:
      - ./job/log:/var/log/psitejob
      - ./job/config/config.json:/usr/local/psitejob/config/config.json:ro
      - ./web/apache/log:/var/log/stuhrs_dk/web:ro
      - ./job/goaccess:/usr/local/psitejob/goaccess
    networks:
    - localnetwork
